name: License Expiration Notifier

on:
  workflow_dispatch:
  # Comment out if you want to stop the schedule.
  schedule:
    - cron: "0 0 * * *"

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

jobs:
  run_checker:
    name: Run
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials from IAM Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'
      - name: Bun Run Deploy
        # If you need to authenticate with a private registry, you can set the BUN_AUTH_TOKEN environment variable.
        # https://github.com/oven-sh/setup-bun
        # env:
        #   BUN_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bun run deploy
